# SPDX-FileCopyrightText: 2020 ash_admin contributors <https://github.com/ash-project/ash_admin/graphs.contributors>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ["REUSE.toml", "priv/static/assets/app*"]
SPDX-FileCopyrightText = "2020 Zach Daniel"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "assets/vendor/topbar.js"
SPDX-FileCopyrightText = "2021 Buu Nguyen"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["assets/vendor/heroicons/*", "assets/vendor/heroicons/**/*"]
SPDX-FileCopyrightText = "2020 Refactoring UI Inc"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "priv/vendor/codemirror*"
SPDX-FileCopyrightText = "2017-2024 Marijn Haverbeke and others"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["priv/vendor/javascript.min.js", "priv/vendor/markdown.min.js"]
SPDX-FileCopyrightText = "2017-2024 Marijn Haverbeke and others"
SPDX-License-Identifier = "MIT"
